version: '3'

tasks:
  precommit:
    desc: Enable git pre-commit hooks
    cmds:
      - pre-commit install
  openapi:build:
    desc: Build OpenAPI HTML with Redocly
    dir: /home/t-tsuji/project/CornellNoteWeb
    cmds:
      - npm exec --yes --package @redocly/cli -- redocly build-docs docs/03-詳細設計/2.API詳細/openapi.yaml -o docs/03-詳細設計/2.API詳細/openapi.html
  openapi:ui:
    desc: Serve OpenAPI HTML in browser
    dir: /home/t-tsuji/project/CornellNoteWeb/docs/03-詳細設計/2.API詳細
    cmds:
      - python -m http.server 4000

  docs:readme:
    desc: Generate docs/README.md
    dir: /home/t-tsuji/project/CornellNoteWeb
    cmds:
      - bash tools/generate-docs-readme.sh

  db:status:
    desc: Show dbmate migration status
    cmds:
      - dbmate --migrations-dir "./migrations" status
  db:up:
    desc: Apply dbmate migrations
    cmds:
      - dbmate --migrations-dir "./migrations" up
  db:down:
    desc: Roll back latest dbmate migration
    cmds:
      - dbmate --migrations-dir "./migrations" down

  mock:serve:
    desc: Start mock app server
    dir: /home/t-tsuji/project/CornellNoteWeb/mock
    cmds:
      - python -m http.server 4001

  mock:test:
    desc: Run Playwright tests against mock
    dir: /home/t-tsuji/project/CornellNoteWeb
    cmds:
      - APP_ENV=mock ./node_modules/.bin/playwright test --update-snapshots

  docker:build:
    desc: Build docker images
    cmds:
      - docker compose build

  docker:up:
    desc: Restart docker compose services
    cmds:
      - docker compose down
      - docker compose up -d
