version: '3'

tasks:
  precommit:
    desc: Enable git pre-commit hooks
    cmds:
      - pre-commit install
  openapi:build:
    desc: Build OpenAPI HTML with Redocly
    dir: /home/t-tsuji/project/CornellNoteWeb
    cmds:
      - npm exec --yes --package @redocly/cli -- redocly build-docs docs/03-詳細設計/2.API詳細/openapi.yaml -o docs/03-詳細設計/2.API詳細/openapi.html
  openapi:ui:
    desc: Serve OpenAPI HTML in browser
    dir: /home/t-tsuji/project/CornellNoteWeb/docs/03-詳細設計/2.API詳細
    cmds:
      - python -m http.server 4000

  docs:readme:
    desc: Generate docs/README.md
    dir: /home/t-tsuji/project/CornellNoteWeb
    cmds:
      - bash tools/generate-docs-readme.sh

  backend:build:
    desc: Build Spring Boot app
    dir: /home/t-tsuji/project/CornellNoteWeb
    cmds:
      - ./gradlew build
  backend:run:
    desc: Run Spring Boot app
    dir: /home/t-tsuji/project/CornellNoteWeb
    cmds:
      - ./gradlew bootRun
  backend:test:
    desc: Run backend unit tests
    dir: /home/t-tsuji/project/CornellNoteWeb
    cmds:
      - ./gradlew test
  backend:check:
    desc: Run backend checks with coverage
    dir: /home/t-tsuji/project/CornellNoteWeb
    cmds:
      - ./gradlew check
  backend:test:class:
    desc: Run single backend test class (CLASS=...)
    dir: /home/t-tsuji/project/CornellNoteWeb
    cmds:
      - ./gradlew test --tests "{{.CLASS}}"
  backend:test:method:
    desc: Run single backend test method (TEST=...)
    dir: /home/t-tsuji/project/CornellNoteWeb
    cmds:
      - ./gradlew test --tests "{{.TEST}}"

  frontend:install:
    desc: Install frontend dependencies
    dir: /home/t-tsuji/project/CornellNoteWeb
    cmds:
      - npm install
  e2e:test:
    desc: Run all Playwright tests
    dir: /home/t-tsuji/project/CornellNoteWeb
    cmds:
      - npm run test:e2e
  e2e:ui:
    desc: Run Playwright tests with UI
    dir: /home/t-tsuji/project/CornellNoteWeb
    cmds:
      - npm run test:e2e:ui
  e2e:file:
    desc: Run single Playwright spec (FILE=...)
    dir: /home/t-tsuji/project/CornellNoteWeb
    cmds:
      - npx playwright test "{{.FILE}}"
  e2e:title:
    desc: Run Playwright tests by title (FILE=..., TITLE=...)
    dir: /home/t-tsuji/project/CornellNoteWeb
    cmds:
      - npx playwright test "{{.FILE}}" -g "{{.TITLE}}"

  infra:install:
    desc: Install infra dependencies
    dir: /home/t-tsuji/project/CornellNoteWeb/infra
    cmds:
      - npm install
  infra:build:
    desc: Build infra (tsc)
    dir: /home/t-tsuji/project/CornellNoteWeb/infra
    cmds:
      - npm run build
  infra:test:
    desc: Run infra tests
    dir: /home/t-tsuji/project/CornellNoteWeb/infra
    cmds:
      - npm test
  infra:test:file:
    desc: Run single infra test file (FILE=...)
    dir: /home/t-tsuji/project/CornellNoteWeb/infra
    cmds:
      - npx jest "{{.FILE}}"
  infra:test:name:
    desc: Run infra test by name (NAME=...)
    dir: /home/t-tsuji/project/CornellNoteWeb/infra
    cmds:
      - npx jest -t "{{.NAME}}"
  infra:synth:
    desc: Run CDK synth
    dir: /home/t-tsuji/project/CornellNoteWeb/infra
    cmds:
      - npm run synth
  infra:deploy:
    desc: Run CDK deploy
    dir: /home/t-tsuji/project/CornellNoteWeb/infra
    cmds:
      - npm run deploy

  db:status:
    desc: Show dbmate migration status
    cmds:
      - dbmate --migrations-dir "./migrations" status
  db:up:
    desc: Apply dbmate migrations
    cmds:
      - dbmate --migrations-dir "./migrations" up
  db:down:
    desc: Roll back latest dbmate migration
    cmds:
      - dbmate --migrations-dir "./migrations" down

  mock:serve:
    desc: Start mock app server
    dir: /home/t-tsuji/project/CornellNoteWeb/mock
    cmds:
      - python -m http.server 4001

  mock:test:
    desc: Run Playwright tests against mock
    dir: /home/t-tsuji/project/CornellNoteWeb
    cmds:
      - APP_ENV=mock ./node_modules/.bin/playwright test --update-snapshots

  docker:build:
    desc: Build docker images
    cmds:
      - docker compose build

  docker:up:
    desc: Restart docker compose services
    cmds:
      - docker compose down
      - docker compose up -d
